### ISSUE TITLE
dnsomatic provider crashing

### ISSUE THREAD

**Issue by diegosc78** [qdm12/ddns-updater#161]
My config.json (first lines...)

```json
{
   "settings":[
      {
         "provider":"dnsomatic",
         "domain":"xxxxxxxxxxx.ddns.net",
         "host":"@",
         "username":"xxxxxxx",
         "password":"xxxxxxx",
         "ip_version": "ipv4"
      },
```

Running in: raspberry (arm64) + docker + kubernetes

Output

```
Running version latest built on 2021-01-29T00:44:25Z (commit 4e94823)


🔧 Need help? https://github.com/qdm12/ddns-updater/issues/new
💻 Email? quentin.mcgaw@gmail.com
☕ Slack? Join from the Slack button on Github
💸 Help me? https://github.com/sponsors/qdm12
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x30da38]

goroutine 1 [running]:
github.com/qdm12/ddns-updater/internal/settings.(*dnsomatic).isValid(0x40005abf10, 0x40005abf10, 0x90)
github.com/qdm12/ddns-updater/internal/settings/dnsomatic.go:57 +0x28
github.com/qdm12/ddns-updater/internal/settings.NewDNSOMatic(0x4000356480, 0x87, 0x90, 0x40005e2ec0, 0x13, 0xa99900, 0x1, 0x400032b688, 0x4, 0x2d8a00, ...)
github.com/qdm12/ddns-updater/internal/settings/dnsomatic.go:49 +0x144
github.com/qdm12/ddns-updater/internal/params.makeSettingsFromObject(0x400032b6e0, 0x9, 0x40005e2ec0, 0x13, 0xa99900, 0x1, 0x400032b688, 0x4, 0x0, 0x0, ...)
github.com/qdm12/ddns-updater/internal/params/json.go:166 +0x334
github.com/qdm12/ddns-updater/internal/params.extractAllSettings(0x400002d500, 0x9e3, 0xa80, 0x400002d500, 0x9e3, 0xa80, 0x400002ca80, 0x9e3, 0x0, 0x0, ...)
github.com/qdm12/ddns-updater/internal/params/json.go:73 +0x1fc
github.com/qdm12/ddns-updater/internal/params.(*reader).getSettingsFromEnv(0x40003caff0, 0x0, 0x400060f7e8, 0x4bb670, 0x40005e2e20, 0x19, 0x40005e2e20, 0x19, 0x1)
github.com/qdm12/ddns-updater/internal/params/json.go:52 +0xb4
github.com/qdm12/ddns-updater/internal/params.(*reader).JSONSettings(0x40003caff0, 0x40005e2e20, 0x19, 0x40005e2e20, 0x19, 0x45d964b800, 0x5c9dbd, 0x5, 0x0, 0x0, ...)
github.com/qdm12/ddns-updater/internal/params/json.go:28 +0x28
main._main(0x7a5600, 0x4000030090, 0x60af60, 0x0)
command-line-arguments/main.go:99 +0x484
main.main()
command-line-arguments/main.go:41 +0x108
```

HINT: same docker image with another config.json (noip provider instead of dnsomatic) works.

**Comment by qdm12** [comment]
Thanks for letting me know! It should  be fixed in https://github.com/qdm12/ddns-updater/commit/78c86b0e244dce48cb3c345b519d4d70b9dcb7d8 you'will just have to re-pull `:latest` once the [build is finished](https://github.com/qdm12/ddns-updater/runs/1798580856). Please let me know if anything doesn't work as I couldn't really test  it (lack of account, time etc. 😄).
