### ISSUE TITLE
Can't Install on Truenas Scale

### ISSUE THREAD

**Issue by RaulGw4** [qdm12/ddns-updater#819]
**TLDR**: *It won't install on Truenas Scale using Discover Apps*

1. Is this urgent: Yes
2. DNS provider(s) you use: Dynu
3. Program version:

    

    `Running App Version 2.9.0; Truenas Version 1.0.30`

4. What are you using to run the container: Truenas Apps Tab

Logs when clicking install:

```log
[EFAULT] Failed to install App: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml Error: INSTALLATION FAILED: execution error at (ddns-updater/templates/common.yaml:5:38): DDNS Updater - Expected non-empty [Host] for dynu provider

 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 511, in __run_body
    rv = await self.method(*args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 210, in nf
    rv = await func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 47, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 187, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 496, in do_create
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1428, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1321, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 49, in helm_action
    raise CallError(f'Failed to {tn_action} App: {errmsg}')
middlewared.service_exception.CallError: [EFAULT] Failed to install App: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
Error: INSTALLATION FAILED: execution error at (ddns-updater/templates/common.yaml:5:38): DDNS Updater - Expected non-empty [Host] for dynu provider
```

Configuration file (**remove your credentials!**):

```json
Application name
- Application Name: ddns-updater
- Version 1.0.30

DDNS Updater Configuration
- Timezone: 'Europe/Bucharest' timezone

DNS Provider Configuration:
- Provider: Dynu
- Domain: filled
- Host (Deprecated): NOT filled as Deprecated
- IP Version: IPv4
- Dynu Username: filled
- Dynu Password: filled
- Dynu Group: NOT filled

- Update Period: 5m
- Update Cooldown Period: 5m
- Backup Period: 24h
- HTTP Timeout: 10s
- Public IP DNS Timeout: 3s

- Shoutrrr Addresses: No items have been added yet.
- Public IP DNS Providers: All providers
- Public IP HTTP Providers: All providers
- Public IPv4 HTTP Providers: All providers
- Public IPv6 HTTP Providers: All providers
- Public IP Fetchers: All providers

- Additional Environment Variables: No items have been added yet.

User and Group Configuration
- User ID: 568
- Group ID: 568

Network Configuration
- Web Port:  30007
- Host network: no

Storage Configuration
- DDNS Updater Data Storage: ixVolume (Dataset created automatically by the system)

Resources Configuration

- CPU: 50m
- Memory: 64Mi

```

Host OS: Truenas Scale

**Comment by RaulGw4** [comment]
It was a Catalog update issue.

The one with the issue was:
App Version: 2.9.0
Chart Version: 1.0.30

And after a forced refresh it found:
App Version: 2.9.0
Chart Version: 1.0.31

No idea why it did that even though it updated half an hour ago.

**Comment by qdm12** [comment]
No problem, probably a chart issue (I'm not the maintainer of the chart)
